---
- name: Create isucon group
  become: yes
  become_user: root
  group:
    name: isucon
    gid: 1001
    state: present
    system: no

- name: Create isucon user
  become: yes
  become_user: root
  user:
    name: isucon
    uid: 1001
    group: isucon
    password: isucon
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  become: yes
  become_user: root
  copy:
    content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/90-isucon-user
    owner: root
    group: root
    mode: 0440

    # - name: Install epel-release
    #   become: yes
    #   become_user: root
    #   yum:
    #     pkg: "{{ item }}"
    #     state: installed
    #   with_items:
    #     - epel-release

    # - name: Install Development Tools
    #   become: yes
    #   become_user: root
    #   apt: name="{{ item }}" state=present
    #   with_items:
    #     - "@Development Tools"

- name: Install packages
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - curl
    - dstat
    - git
    - jq
    - sudo
    - ubuntu-dev-tools
    - build-essential
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libssl-dev

- name: Install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /home/isucon/xbuild
    version: master

- name: mkdir /home/isucon/local for xbuild
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/local
    state=directory
