# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "bento/ubuntu-18.04"
# box = "ubuntu/xenial64"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.define "isucon1" do |m|
    m.vm.network "private_network", ip: "10.0.3.101"
  end
  config.vm.define "isucon2" do |m|
    m.vm.network "private_network", ip: "10.0.3.102"
  end
  config.vm.define "isucon3" do |m|
    m.vm.network "private_network", ip: "10.0.3.103"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt install python
  SHELL
end
